export * from './categoria.repository';
export * from './cliente.repository';
export * from './detalle-pedido.repository';
export * from './pedido.repository';
export * from './persona.repository';
export * from './petshop.repository';
export * from './producto.repository';
export * from './tipo-mascota.repository';
export * from './usuario-administrador.repository';
